### ISSUE TITLE
documentation question

### ISSUE THREAD

**Issue by arakotom** [yuxiangw/autodp#11]
Hi,

thanks a lot for this work. It is very helpful.

Just one quick issue : what is the role of coeff in the compose_subsampled_mechanism?

thanks a lot

A.

**Comment by jeremy43** [comment]
Hi,
It's the number of times that the subsampled mechanism is being composed.

**Comment by yuxiangw** [comment]
Closing this issue.  The use of the new API would be preferred. This will be related to the ``autodp.transformer_zoo.composition``
