### ISSUE TITLE
issue with "privacy_calibrator.subsample_epsdelta_inverse(eps,delta,prob=gamma)"

### ISSUE THREAD

**Issue by dadelani** [yuxiangw/autodp#2]
Thanks for making this tool available for DP research, I appreciate the great work.

I was going through your tutorial on privacy calibrator (section 4) https://github.com/yuxiangw/autodp/blob/master/tutorials/tutorial_privacy_calibrator.ipynb

Not sure if the function "privacy_calibrator.subsample_epsdelta_inverse(eps, delta, gamma) is giving the right answer.  For example

eps = 1
delta = 1e-6
gamma = 0.01
### First, apply subsampling lemma to calibrate the basic privacy needed
eps0,delta0 = privacy_calibrator.subsample_epsdelta_inverse(eps,delta,prob=gamma)
### Then we can get the amount of noise needed from the base mechanism
print((eps0,delta0))
params = privacy_calibrator.gaussian_mech(eps0,delta0)
print(f'Gaussian: eps,delta,gamma = ({eps},{delta},{gamma}) ==> Noise level sigma=',params['sigma'])
## Gaussian: eps,delta,gamma = (1,1e-06,0.01) ==> Noise level sigma= 0.9366237019634324

However, I was expecting sigma = 1.258483615711703 
similar to the result when we try

params = privacy_calibrator.gaussian_mech(eps,delta,prob=gamma)
print(f'Gaussian: eps,delta,gamma = ({eps},{delta},{gamma}) ==> Noise level sigma=',params['sigma'])
## Gaussian: eps,delta,gamma = (1,1e-06,0.01) ==> Noise level sigma= 1.258483615711703

**Comment by yuxiangw** [comment]
Thank you! I believe this has already been fixed by handling a corner case separately.
