### ISSUE TITLE
Issue with SSP_scale and AdaSSP_scale inheritance

### ISSUE THREAD

**Issue by pvarshney1729** [yuxiangw/autodp#22]
I was running the tutorial_AdaSSP_vs_noisyGD.ipynb Tutorial Notebook on Google Colab. I encountered the following issue while running the 4th Cell Block of the notebook:

`AttributeError: 'SSP_scale' object has no attribute 'set_all_representation'`.

The expanded error is as follows:

![Screenshot 2021-09-20 9 08 06 PM](https://user-images.githubusercontent.com/40918168/134031195-fbdbf317-5bb5-4c8b-897f-ff2e1141b4dd.png)
![Screenshot 2021-09-20 9 08 48 PM](https://user-images.githubusercontent.com/40918168/134031207-bc4f584c-f5f5-46d9-8b3e-f47a747d5faa.png)

Kindly have a look at the earliest @yuxiangw. Thanks in advance!

**Comment by yuxiangw** [comment]
The "pip install" version is not updated.  You may take the version in either the master branch or the "new_tutorials" branch and they both should work.  We will work to update the "pip install" version later today.

**Comment by yuxiangw** [comment]
Hi, just a message to say that the "pip install" version should work now.  Also all tutorials are merged into the master branch.  Closing the issue now.  Let me know if you are running into additional issues.
